#!/usr/bin/env node --no-warnings
/* eslint-env node */
/* eslint-disable es5/no-spread */

// commander has zero dependencies, unlike gulp
const program = require("commander");
const pjson = require("./package.json");
const { deploy } = require("./scripts/deploy");
const { hashContainer } = require("./scripts/integrity");

program.version(pjson.version);

program
  .command("deploy <env>")
  .description("Deploy code to <env> (dev, nightly, qa, rc, prod)")
  .option("-r, --redo", "Don't bump version, redeploy current version")
  .action(deploy);

program
  .command("hash <container>")
  .description("Generate integrity hash code for <container> (staging, production)")
  .option("-e, --env <env>", "FCP server env (prod, stg, qa, qa2, dev)", "prod")
  .option("-s, --sitekey <sitekey>", "Sitekey to use (default: use configured one)")
  .option("-a, --algo <algo>", "Hash algorithm to use", "sha256")
  .action(handleErrors(hashContainer));

program.parse(process.argv);

/**
 * Handle async/await errors
 */
function handleErrors(fn) {
  return function(...args) {
    return fn(...args).catch(err => {
      console.error(err.stack || err);
      // eslint-disable-next-line no-process-exit
      process.exit(1);
      return null;
    });
  };
}
