/**
 * The CSS for the UI portions of the replay player.
 *
 * (c) Copyright 2018 ForeSee Results, Inc.
 */

import { makeAssetURI } from "../../../fs/index";

const UICSS = {
  playbackFrameBorder: 2,
  // CC-4575 Fade animations are too heavy for Preplayer machines(no GPU)
  // The animation may be done "manually" instead of relying on the CSS
  // animation system.
  overlayShadeFadeTime: 0,
  overlayShadeSkipTime: 1500,
};

UICSS.pathFSLogo = makeAssetURI("/fslogo.svg");

UICSS.data = [
  "body {",
  "  background-color: #777;",
  "  padding: 0;",
  "  margin: 0;",
  "  width: 100%;",
  "  height: 100vh;",
  "  display: flex;",
  "  justify-content: center;",
  "  align-items: center;",
  "  overflow: hidden;",
  "}",
  "",
  "/************",
  " * iframe",
  " ************/",
  "",
  "iframe#playback {",
  "  border: ",
  `${UICSS.playbackFrameBorder}px solid #333;`,
  "  background-color: #fff;",
  "  box-shadow: 10px 10px 10px #555;",
  "}",
  "",
  "/************",
  " * UI",
  " ************/",
  "",
  ".overlay {",
  "  z-index: 901;",
  "  position: absolute;",
  // "  transition-property: width, height, zoom;",
  // "  transition-timing-function: ease-in;",
  // "  transition-duration: ", Math.round(UICSS.overlayShadeFadeTime) + "ms;",
  "}",
  "",
  ".overlay>div>* {",
  "  transition: opacity ",
  `${Math.round(UICSS.overlayShadeFadeTime)}ms ease-in;`,
  "}",
  "",
  ".overlay .hidden {",
  "  opacity: 0;",
  "}",
  "",
  ".overlay .center {",
  "  position: absolute;",
  "  top: 50%;",
  "  left: 50%;",
  "  transform: translate(-50%, -50%);",
  "}",
  "",
  "#shade {",
  "  width: 100%;",
  "  height: 100%;",
  `  background-image: url('${UICSS.pathFSLogo}');`,
  "  background-color: #fff;",
  "  background-repeat: no-repeat;",
  "  background-position: 50% 50%;",
  "  background-size: 30%;",
  "  filter: grayscale(1) brightness(2.5) invert(1);",
  "}",
  "",
  "#shade.pageEnd {",
  "  filter: grayscale(1) brightness(2.5);",
  "}",
  "",
  "#progress {",
  "  height: 5%;",
  "  background-color: #444;",
  "  position: relative;",
  "  top: 90%;",
  "}",
  "",
  "#counter {",
  "  width: 100%;",
  "  height: 100%;",
  "  background-color: #000d;",
  "  color: #fff;",
  "}",
  "",
  "#counter #graph {",
  "  position: absolute;",
  "  width: 16em;",
  "  top: 50%;",
  "  left: 50%;",
  "  transform: translate(-50%, -50%);",
  "  z-index: -1;",
  "}",
  "",
  "#counter #graph circle#c {",
  "  stroke: #7db1ef95;",
  "  cx: 0.5;",
  "  cy: 0.5;",
  "  r: 0.25;",
  "  fill: none;",
  "  stroke-width: 0.5px;",
  "  stroke-dashoffset: 1.57;",
  "  transition: stroke-dashoffset ",
  `${Math.round(UICSS.overlayShadeSkipTime)}ms linear;`,
  "  stroke-dasharray: 1.57;",
  "  transform: translate(0%, 100%) rotate(-90deg);",
  "}",
  "",
  "#counter #caption{",
  "  position: absolute;",
  "  top: 50%;",
  "  left: 50%;",
  "  transform: translate(-50%, -50%);",
  "  z-index: -1;",
  '  font-family: "Helvetica Neue", "Liberation Sans", sans-serif;',
  "  font-size: 32pt;",
  "}",
].join("\n");

export { UICSS };
